//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UsbHidDemonstrator.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GRAPHIC_CONFIG              101
#define IDD_USBHIDDEMONSTRATOR_DIALOG   102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDD_DESCRIPTOR_VIEW             129
#define IDD_FEATURE_VIEW                130
#define IDD_REPORT_VIEW                 131
#define IDD_GRAPHIC_VIEW                132
#define IDI_ICON_LED_OFF                140
#define IDI_ICON_LED_ON                 141
#define IDI_ICON1                       144
#define IDI_ICON2                       145
#define IDI_ICON4                       147
#define IDI_ICON3                       150
#define IDI_ICON5                       151
#define IDB_BITMAP1                     162
#define IDC_COMBO1                      1002
#define IDC_HID_TARGETS                 1002
#define IDC_SHOW_DESCROPTOR_VIEW        1003
#define IDC_SHOW_FEATURE_VIEW           1004
#define IDC_SHOW_REPORT_VIEW            1005
#define IDC_SHOW_GRAPHIC_VIEW           1006
#define IDC_FRAMES_CONTAINER            1007
#define IDC_GRAPHIC_CONFIG              1008
#define IDC_HEX_EDITOR                  1011
#define IDC_OUTPUT_HEX_EDITOR           1011
#define IDC_SIZE_HEX_EDIT               1012
#define IDC_SIZE_OUTPUT_HEX_EDIT        1012
#define IDC_TARGETS_CTRL                1013
#define IDC_HEX_EDITORFORREAD           1013
#define IDC_INPUT_HEX_EDITOR            1013
#define IDC_PID                         1014
#define IDC_SIZE_INPUT_HEX_EDIT         1014
#define IDC_VID                         1015
#define IDC_VERSION                     1016
#define IDC_ROLLER1                     1016
#define IDC_Capabilities                1017
#define IDC_ROLLER2                     1017
#define IDC_RV1                         1018
#define IDC_BUTTON1                     1019
#define IDC_BUTTON2                     1020
#define IDC_BUTTON3                     1021
#define IDC_BUTTON4                     1022
#define IDC_BUTTON5                     1023
#define IDC_BUTTON6                     1024
#define IDC_BUTTON7                     1025
#define IDC_RID_BUTTON1                 1026
#define IDC_RID_BUTTON2                 1027
#define IDC_RID_BUTTON3                 1028
#define IDC_RID_BUTTON4                 1029
#define IDC_RID_BUTTON5                 1030
#define IDC_RID_BUTTON6                 1031
#define IDC_RID_BUTTON7                 1032
#define IDC_RID_ROLLER1                 1033
#define IDC_RID_ROLLER2                 1034
#define IDC_RV2                         1035
#define IDC_LED1_ON_OFF                 1036
#define IDC_LED2_ON_OFF                 1037
#define IDC_LED3_ON_OFF                 1038
#define IDC_SLIDER1                     1039
#define IDC_VARIABLE                    1039
#define IDC_LED1                        1040
#define IDC_WRITE_BTN                   1040
#define IDC_LED2                        1041
#define IDC_LED3                        1042
#define IDC_RID_VARIABLE                1043
#define IDC_RID_LED1                    1044
#define IDC_RID_LED2                    1045
#define IDC_RID_LED3                    1046
#define IDC_VI                          1047
#define IDC_BL1                         1048
#define IDC_BL2                         1049
#define IDC_BL3                         1050
#define IDC_BL4                         1051
#define IDC_BL5                         1052
#define IDC_BL6                         1053
#define IDC_BL7                         1054
#define IDC_VL                          1055
#define IDC_RL1                         1056
#define IDC_RL2                         1057
#define IDC_CHECK1                      1058
#define IDC_LED4_ON_OFF                 1058
#define IDC_CHECK2                      1059
#define IDC_LED5                        1059
#define IDC_LED4                        1059
#define IDC_CHECK3                      1060
#define IDC_RID_LED4                    1060
#define IDC_CHECK4                      1061
#define IDC_CHECK5                      1062
#define IDC_SHB1                        1062
#define IDC_CHECK6                      1063
#define IDC_SHB2                        1063
#define IDC_CHECK7                      1064
#define IDC_SHB3                        1064
#define IDC_CHECK8                      1065
#define IDC_SHB4                        1065
#define IDC_CHECK9                      1066
#define IDC_SHB5                        1066
#define IDC_CHECK10                     1067
#define IDC_SHB7                        1067
#define IDC_CHECK11                     1068
#define IDC_SHB6                        1068
#define IDC_CHECK12                     1069
#define IDC_SHL1                        1069
#define IDC_EDIT1                       1070
#define B1                              1070
#define IDC_EDIT2                       1071
#define B2                              1071
#define IDC_CAPABILITIES_LIST           1071
#define IDC_EDIT3                       1072
#define B3                              1072
#define IDC_EDIT4                       1073
#define B4                              1073
#define IDC_LOGO                        1073
#define IDC_EDIT5                       1074
#define B5                              1074
#define IDC_BK                          1074
#define IDC_EDIT6                       1075
#define B6                              1075
#define IDC_SET_FEATURE                 1075
#define IDC_EDIT7                       1076
#define B7                              1076
#define IDC_GET_FEATURE                 1076
#define IDC_CHECK13                     1077
#define IDC_SHL2                        1077
#define IDC_CHECK14                     1078
#define IDC_SHL3                        1078
#define IDC_EDIT8                       1079
#define L1                              1079
#define IDC_USE_SET_REPORT              1079
#define IDC_EDIT9                       1080
#define L2                              1080
#define IDC_USE_SET_FEATURE             1080
#define IDC_EDIT10                      1081
#define L3                              1081
#define IDC_CHECK15                     1082
#define IDC_SHVO                        1082
#define IDC_EDIT11                      1083
#define VO                              1083
#define IDC_CHECK16                     1084
#define IDC_SHVI1                       1084
#define IDC_EDIT12                      1085
#define VI1                             1085
#define IDC_SHVI2                       1086
#define VI2                             1087
#define IDC_SHL4                        1088
#define L4                              1089

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
